MySocialMedia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('chat.urls')),
    path('', include('comment.urls')),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/urls.py
from django.urls import path
from .views import *

app_name = "chat"

urlpatterns = [
    path('inbox/', ListThreads.as_view(), name='inbox'),
    path('inbox/create_thread', CreatThread.as_view(), name='create_thread'),
    path('inbox/<int:pk>/', ThreadView.as_view(), name='thread'),
    path('inbox/<int:pk>/create_message', CreateMessage.as_view(), name='create_message'),
]

chat/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model


User = get_user_model()


class ThreadModel(models.Model):
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE,
                             related_name='+')
    receiver = models.ForeignKey(User,
                                 on_delete=models.CASCADE,
                                 related_name='+')


class MessageModel(models.Model):
    thread = models.ForeignKey(ThreadModel,
                               on_delete=models.CASCADE,
                               related_name='+',
                               blank=True,
                               null=True)
    sender_user = models.ForeignKey(User,
                                    on_delete=models.CASCADE,
                                    related_name='+')
    receiver_user = models.ForeignKey(User,
                                      on_delete=models.CASCADE,
                                      related_name='+')
    body = models.CharField(max_length=1000)
    image = models.ImageField(upload_to='messages_photos', blank=True, null=True)
    date = models.DateTimeField(default=timezone.now)
    is_read = models.BooleanField(default=False)

chat/forms.py
from django import forms


class ThreadForm(forms.Form):
    username = forms.CharField(label='',
                               max_length=100)


class MessageForm(forms.Form):
    message = forms.CharField(label='', max_length=1000)

chat/views.py
from django.db.models import Q
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth.models import User
from .models import ThreadModel, MessageModel
from .forms import ThreadForm, MessageForm


class ListThreads(View):
    def get(self, request, *args, **kwargs):
        threads = ThreadModel.objects.filter(Q(user=request.user) | Q(receiver=request.user))
        return render(request, 'chat/inbox.html', {'threads': threads})


class CreatThread(View):
    def get(self, request, *args, **kwargs):
        form = ThreadForm()
        return render(request, 'chat/creat_thread.html', {'form': form})

    def post(self, request, *args, **kwargs):
        form = ThreadForm(request.POST)
        username = request.POST['username']

        try:
            receiver = User.objects.get(username=username)
            if ThreadModel.objects.filter(user=request.user, receiver=receiver).exists():
                thread = ThreadModel.objects.filter(user=request.user, receiver=receiver)[0]
                return redirect('thread', pk=thread.pk)
            elif ThreadModel.objects.filter(user=receiver, receiver=request.user).exists():
                thread = ThreadModel.objects.filter(user=receiver, receiver=request.user)[0]
                return redirect('thread', pk=thread.pk)

            if form.is_valid():
                thread = ThreadModel(
                    user=request.user,
                    receiver=receiver
                )
                thread.save()

                return redirect('chat:thread', pk=thread.pk)
        except:
            return redirect('chat:create_thread')


class ThreadView(View):
    def get(self, request, pk, *args, **kwargs):
        form = MessageForm()
        thread = ThreadModel.objects.get(pk=pk)
        message_list = MessageModel.objects.filter(thread__pk__contains=pk)

        return render(request, 'chat/thread.html', {'form': form,
                                                    'thread': thread,
                                                    'message_list': message_list})


class CreateMessage(View):
    def post(self, request, pk, *args, **kwargs):
        thread = ThreadModel.objects.get(pk=pk)

        if thread.receiver == request.user:
            receiver = thread.user
        else:
            receiver = thread.receiver

        message = MessageModel(thread=thread,
                               sender_user=request.user,
                               receiver_user=receiver,
                               body=request.POST['message'])
        message.save()

        return redirect('chat:thread', pk=pk)

templates/chat/creat_thread.html
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

</head>
<body>

<div class="container">
  <div class="row mt-5">
    <div class="col-md-3 col-sm-6">
      <a href="{% url 'chat:inbox' %}" class="btn btn-light">Back to Your Inbox</a>
    </div>
  </div>
  <div class="row justify-content-center mt-5">
    <div class="col-md-5 col-sm-12">
      <h5>Start a Conversation!</h5>
    </div>
  </div>
  <div class="row justify-content-center mt-3 mb-5">
    <div class="col-md-5 col-sm-12">
      <form method="POST">
        {% csrf_token %}
        <p>Enter the username for the person you would like to talk to.</p>
        {{ form | crispy }}
        <div class="d-grid gap-2">
        <button type="submit" class="btn btn-success mt-3">Continue</button>
        </div>
      </form>
    </div>
  </div>
</div>

</body>
</html>

templates/chat/inbox.html
{% load crispy_forms_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!-- CSS only -->
    <link href="{% static 'assets/images/favicon.png' %}" rel="icon" type="image/png">
    <title>Settings</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'assets/css/icons.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/uikit.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/tailwind.css' %}">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
      rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
      crossorigin="anonymous">
</head>
<body>

<div class="container">
  <div class="row">
    <div class="col-md-12 p-5">
        <h1 class="text-2xl leading-6 text-gray-900 tracking-tight mt-3"><a href="{% url 'index' %}">Home</a></h1>
        <hr>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 p-5">
      <form method="GET" action="{% url 'chat:create_thread' %}">
        <button class="btn btn-light p-3" type="submit">Start a Conversation</button>
      </form>
    </div>
  </div>

        {% for thread in threads.all %}
            {% if thread.receiver == request.user %}
              <div class="row mb-3">
                <div class="card col-md-12 p-5 shadow-sm">
                  <h5>{{ thread.user }}</h5>
                  <a class="stretched-link" href="{% url 'chat:thread' thread.pk %}"><h5></h5></a>
                </div>
              </div>
            {% else %}
            <div class="row mb-3">
                <div class="card col-md-12 p-5 shadow-sm">
                  <h5>{{ thread.receiver }}</h5>
                  <a class="stretched-link" href="{% url 'chat:thread' thread.pk %}"><h5></h5></a>
                </div>
              </div>
            {% endif %}
        {% endfor %}
</div>


</body>
</html>

templates/chat/thread.html
{% load static %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://kit.fontawesome.com/1d71f92e0a.js" crossorigin="anonymous"></script>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <link href="{% static 'js/../../static/css/style.css' %}" rel="stylesheet">

    <!-- Option 1: Bootstrap Bundle with Popper -->

    <link href="{% static 'js/../../static/css/style.css' %}" rel="stylesheet">

</head>
<body>
  <div class="container">
    <div class="row">
      <div class="card col-md-12 mt-5 p-3 shadow-sm">
        {% if thread.receiver == request.user %}
				<h5>@{{ thread.user }}</h5>
			{% else %}
				<h5>@{{ thread.receiver }}</h5>
			{% endif %}
      </div>
    </div>

    {% if message_list.all.count == 0 %}
    <div class="row my-5">
      <div class="col-md-12">
        <p class="empty-text">No Messages</p>
      </div>
    </div>
    {% endif %}

    {% for message in message_list %}
    <div class="row">
      <div class="col-md-12 my-1">
        {% if message.sender_user == request.user %}
      <div class="sent-message my-3">
        <p>{{ message.body }}</p>
      </div>
    {% elif message.receiver_user == request.user%}
    <div class="received-message my-3">
      <p>{{ message.body }}</p>
    </div>
    {% endif %}
    </div>
  </div>
  {% endfor %}

  <div class="row">
    <div class="card col-md-12 p-3 shadow-sm">
      <form method="POST" action="{% url 'chat:create_message' thread.pk %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form | crispy }}
        <div class="d-grid gap-2 mt-3">
          <button class="btn btn-light" type="submit">Send Message</button>
        </div>
      </form>
    </div>
  </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
  <script type="text/javascript" src="{% static 'js/social.js' %}"></script>
</body>
</html>